[book]
authors = ["Aj4x"]
language = "en"
multilingual = false
src = "src"
title = "Ramblings"

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/Aj4x/notes/tree/main/src"
edit-url-template = "https://github.com/Aj4x/notes/tree/main/src/{path}"
